spring:
#连接池
  datasource:
    url: jdbc:mysql://localhost:3306/community
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#mail
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    username: 642789558@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: wptipmkoniuxbeia
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
#QQ的:wptipmkoniuxbeia
  #ASVLNKHDYTPSWEKX
  #开发时先关闭缓存
  thymeleaf:
    cache: false
#redis
  redis:
    database: 11
    host: localhost
    port: 6379

#kafkaProperties
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: community-consumer-group
#是否提交消费者的
      enable-auto-commit: true
#      自动提交频率:3秒
      auto-commit-interval: 3000

#mybatis配置

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dongppman.community.entity
  configuration:
    #开启自增
    use-generated-keys: true
    #字段不区分大小写,所以如果大写字母往往用下划线保存,user_name=userName而这个支持两者能够匹配
    map-underscore-to-camel-case: true

server:
  servlet:
    context-path: /community

#community
community.path.domain: http://localhost:8080
community.path.upload: e:/community/upload



